# Generated by Django 6.0.2 on 2026-03-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nole', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
